"""add_alert_history_fields

Revision ID: 2bfd451b4aed
Revises: 
Create Date: 2026-07-09 03:07:36.190343
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2bfd451b4aed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('alerts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('alerts', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('polygons', sa.Text(), nullable=True))
    op.add_column('alerts', sa.Column('source', sa.String(length=50), nullable=True))
    op.alter_column('alerts', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'source')
    op.drop_column('alerts', 'polygons')
    op.drop_column('alerts', 'expired_at')
    op.drop_column('alerts', 'is_active')
    # ### end Alembic commands ###
